### ISSUE TITLE
Repo id is not being properly associated when creating issues

### ISSUE THREAD

**Issue by awaxman11** [CarlosPlusPlus/ghanban#13]
![](http://cl.ly/a1cI/Image%202015-03-03%20at%208.05.04%20AM.png)

@CarlosPlusPlus shouldn't ```self.issues << i ``` do that in repo.rb?

![](http://cl.ly/a17A/Image%202015-03-03%20at%208.05.37%20AM.png)

**Comment by CarlosPlusPlus** [comment]
Assuming you put a `debugger` or a `binding.pry` in the `add_issues` method?

If this is the case, remember that no IDs will be assigned until the high level association of `@board` is saved back in `BoardsController#create`. I'm thinking this may not be an actual issue - can you verify that for us by checking the state of the issues _after_ `@board.save` and seeing if the ID's were assigned correctly?

**Comment by awaxman11** [comment]
I did have a binding.pry in there ha, although when I removed it it's still not working...about to head out for a classpass but will keep looking into it a little later. Thanks for the quick response!

**Comment by awaxman11** [comment]
>I'm thinking this may not be an actual issue

@CarlosPlusPlus you are correct sir

![](http://cl.ly/a2bJ/Image%202015-03-03%20at%208.41.42%20PM.png)
